import { test, expect } from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('gd-settings',JSON.stringify({graphics:'LOW'})));});
test('menu, keyboard steering, braking, pause, settings and restart',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:'NO WHEEL. JUST INSTINCT.'})).toBeVisible();
 await page.getByRole('button',{name:'HOW TO PLAY',exact:true}).click();await expect(page.getByText('Close your fist to brake')).toBeVisible();await page.getByRole('button',{name:'GOT IT'}).click();
 await page.getByRole('button',{name:'No camera? Try keyboard mode'}).click();await page.keyboard.press('ArrowLeft');await expect(page.locator('.lane-indicator')).toContainText('LANE 2 / 4',{timeout:30000});
 await expect.poll(async()=>Number(await page.locator('.speed-inner strong').innerText()),{timeout:30000}).toBeGreaterThan(20);await page.keyboard.down('Space');await expect(page.locator('.speed-inner strong')).toHaveText('000',{timeout:30000});await page.keyboard.up('Space');await expect.poll(async()=>Number(await page.locator('.speed-inner strong').innerText()),{timeout:30000}).toBeGreaterThan(10);
 await page.keyboard.press('Escape');await expect(page.getByRole('heading',{name:'PAUSED'})).toBeVisible();const score=await page.locator('.hud-left strong').innerText();await page.waitForTimeout(300);await expect(page.locator('.hud-left strong')).toHaveText(score);
 await page.getByRole('button',{name:'SETTINGS',exact:true}).click();await page.getByRole('combobox').first().selectOption('LOW');await page.getByRole('button',{name:'SAVE & CLOSE'}).click();await page.getByRole('button',{name:'RESTART',exact:true}).click();await expect(page.locator('.lane-indicator')).toContainText('LANE 3 / 4');await page.screenshot({path:'/tmp/gesture-race.png'});await page.keyboard.press('Escape');await page.getByRole('button',{name:'MAIN MENU',exact:true}).click();await page.waitForTimeout(1100);await page.screenshot({path:'/tmp/gesture-menu.png'});expect(errors).toEqual([]);
});
test('camera permission, local WASM model initialization, detection and track cleanup',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const cameraRequests:string[]=[];page.on('request',r=>{if(r.url().includes('mediapipe'))cameraRequests.push(r.url());});await page.goto('/');await page.getByRole('button',{name:'PLAY',exact:true}).click();await page.getByRole('button',{name:'ENABLE CAMERA',exact:true}).click();await expect(page.getByRole('heading',{name:'Find your flow.'})).toBeVisible({timeout:60000});await expect(page.locator('.footer')).toContainText('CAMERA ACTIVE');await page.screenshot({path:'/tmp/gesture-camera.png'});expect(cameraRequests.some(u=>u.includes('hand_landmarker.task'))).toBeTruthy();expect(cameraRequests.every(u=>u.startsWith('http://127.0.0.1:5173/'))).toBeTruthy();await page.getByRole('button',{name:'Back to menu'}).click();await page.getByRole('button',{name:'TURN OFF CAMERA',exact:true}).click();await expect(page.locator('.footer')).toContainText('CAMERA OFF');expect(errors).toEqual([]);
});
