import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Simulation,LANES} from '../src/game/Simulation';
import {GestureSmoothing,recognize,type Point} from '../src/handTracking/GestureRecognizer';
function advance(s:Simulation,seconds:number){for(let i=0;i<seconds*60;i++)s.update(1/60);}
test('steering eases to lane and stays inside the road',()=>{const s=new Simulation();s.reset(true);s.command('LEFT');s.update(.1);assert.ok(s.x>LANES[1]&&s.x<LANES[2]);advance(s,1);assert.equal(s.x,LANES[1]);s.command('LEFT');advance(s,1);s.command('LEFT');advance(s,1);assert.equal(s.lane,0);assert.equal(s.x,LANES[0]);});
test('fist stops smoothly; missing hand preserves braking; open hand accelerates',()=>{const s=new Simulation();s.reset(true);advance(s,4);assert.equal(s.speed,80);s.command('FIST');s.update(.1);assert.ok(s.speed>0&&s.speed<80);s.command('NO_HAND');advance(s,3);assert.equal(s.speed,0);s.command('NEUTRAL');advance(s,3);assert.equal(s.speed,80);});
test('pause freezes position speed traffic score and distance',()=>{const s=new Simulation();s.reset();advance(s,4);s.phase='paused';const before=JSON.stringify(s);advance(s,10);assert.equal(JSON.stringify(s),before);});
test('collision ends a race; restart resets score and bonus counters',()=>{const s=new Simulation();s.reset();Object.assign(s.traffic[0],{active:true,lane:2,z:-2,speed:0});s.update(.016);assert.equal(s.phase,'crash');s.nearMisses=3;s.reset();assert.equal(s.nearMisses,0);assert.equal(s.score,0);assert.ok(s.traffic.every(c=>!c.active));});
test('traffic rows reserve free lanes and overtakes award points',()=>{const s=new Simulation(()=>.2);s.reset();s.elapsed=40;advance(s,4);const lanes=new Set(s.traffic.filter(c=>c.active).map(c=>c.lane));assert.ok(lanes.size<=2);s.traffic.forEach(c=>c.active=false);Object.assign(s.traffic[0],{active:true,lane:0,z:4.4,speed:0,passed:false});s.speed=100;s.update(.1);assert.equal(s.avoided,1);s.update(.1);assert.ok(s.score>=50);});
test('smoothing rejects flicker, confirms stable gesture, emits one held command and rearms',()=>{const f=new GestureSmoothing();let commands:string[]=[];for(let i=0;i<20;i++){const r=f.update({gesture:i%2?'LEFT':'RIGHT',confidence:.95},i*40);if(r.command)commands.push(r.command);}assert.equal(commands.length,0);for(let i=20;i<100;i++){const r=f.update({gesture:'LEFT',confidence:.95},i*40);if(r.command)commands.push(r.command);}assert.deepEqual(commands,['LEFT']);for(let i=100;i<120;i++)f.update({gesture:'NEUTRAL',confidence:.95},i*40);for(let i=120;i<140;i++){const r=f.update({gesture:'LEFT',confidence:.95},i*40);if(r.command)commands.push(r.command);}assert.deepEqual(commands,['LEFT','LEFT']);});
test('low confidence cannot issue a command',()=>{const f=new GestureSmoothing();for(let i=0;i<40;i++)assert.equal(f.update({gesture:'FIST',confidence:.4},i*40).command,null);});
test('landmark direction accounts for mirrored preview',()=>{const p:Point[]=Array.from({length:21},()=>({x:.5,y:.6}));p[0]={x:.5,y:.9};p[9]={x:.5,y:.6};for(const tip of [12,16,20]){p[tip-2]={x:.5,y:.5};p[tip]={x:.5,y:.68};}p[5]={x:.5,y:.65};p[6]={x:.65,y:.65};p[8]={x:.9,y:.65};assert.equal(recognize(p,true).gesture,'LEFT');assert.equal(recognize(p,false).gesture,'RIGHT');assert.equal(recognize([]).gesture,'NO_HAND');});
test('closed fist brakes; raised thumb is not a fist',()=>{const p:Point[]=Array.from({length:21},()=>({x:.5,y:.6}));p[0]={x:.5,y:.9};p[9]={x:.5,y:.6};p[5]={x:.4,y:.65};p[4]={x:.47,y:.66};for(const tip of [8,12,16,20]){p[tip-2]={x:.5,y:.5};p[tip]={x:.5,y:.68};}assert.equal(recognize(p).gesture,'FIST');p[4]={x:.5,y:.1};assert.equal(recognize(p).gesture,'NEUTRAL');});
