import { useEffect, useRef } from 'react';
import { Camera, Hand } from 'lucide-react';
import type { HandTracker, Tracking } from '../handTracking/HandTracker';
const connections=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[0,17],[17,18],[18,19],[19,20]];
export function CameraPreview({tracker,result,active,mirror,landmarks,large=false}:{tracker:HandTracker;result:Tracking;active:boolean;mirror:boolean;landmarks:boolean;large?:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{let id=0;const draw=()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,c.width,c.height);if(active&&tracker.video.readyState>=2){ctx.save();if(mirror){ctx.translate(c.width,0);ctx.scale(-1,1);}ctx.drawImage(tracker.video,0,0,c.width,c.height);if(landmarks){ctx.strokeStyle='#91f1da';ctx.lineWidth=2;ctx.fillStyle='#e2fff8';for(const [a,b]of connections){const p=result.points[a],q=result.points[b];if(!p||!q)continue;ctx.beginPath();ctx.moveTo(p.x*c.width,p.y*c.height);ctx.lineTo(q.x*c.width,q.y*c.height);ctx.stroke();}for(const p of result.points){ctx.beginPath();ctx.arc(p.x*c.width,p.y*c.height,3,0,Math.PI*2);ctx.fill();}}ctx.restore();}id=requestAnimationFrame(draw);};draw();return()=>cancelAnimationFrame(id);},[tracker,result,active,mirror,landmarks]);
 return <div className={`camera-panel ${large?'large':''}`}><div className="camera-heading"><Camera size={13}/><span>HAND TRACKING</span><i className={active&&result.points.length?'live':''}/></div><div className="camera-image"><canvas ref={canvas} width={440} height={320}/>{!active&&<div className="camera-placeholder"><Hand size={28}/><span>Your hands. Your controls.</span><small>Camera is off</small></div>}<span className="camera-status"><i className={active&&result.points.length?'live':''}/>{active?result.points.length?'TRACKING':'NO HAND':'CAMERA OFF'}</span><span className="corner tl"/><span className="corner br"/></div><div className="camera-footer"><span>{result.gesture==='FIST'?'✊ STOP':result.gesture==='LEFT'?'← LEFT':result.gesture==='RIGHT'?'RIGHT →':'— NEUTRAL'}</span><small>{active&&result.points.length?`${Math.round(result.confidence*100)}% CONFIDENCE`:'LOCAL · PRIVATE'}</small></div></div>;
}
