import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, Camera, Hand, ShieldCheck, Volume2, VolumeX, Settings2, X, Pause, Play, RotateCcw, MoveLeft, MoveRight, Keyboard, Check, Maximize, Gauge, Route, Trophy, Sun, CircleHelp } from 'lucide-react';
import { Simulation, type Command } from './game/Simulation';
import { World } from './game/World';
import { HandTracker, type Tracking } from './handTracking/HandTracker';
import { AudioManager } from './audio/AudioManager';
import { CameraPreview } from './ui/CameraPreview';
type Screen='menu'|'access'|'calibration'|'tutorial'|'race'|'paused'|'crash';
type Settings={music:number;sfx:number;muted:boolean;graphics:string;sensitivity:string;landmarks:boolean;preview:boolean;mirror:boolean};
const defaults:Settings={music:20,sfx:45,muted:false,graphics:'HIGH',sensitivity:'MEDIUM',landmarks:true,preview:true,mirror:true};
function readSettings(){try{return {...defaults,...JSON.parse(localStorage.getItem('gd-settings')||'{}')};}catch{return defaults;}}
function readNumber(key:string){try{return Number(localStorage.getItem(key))||0;}catch{return 0;}}
function save(key:string,value:string){try{localStorage.setItem(key,value);}catch{/* Storage is optional in private browsing. */}}
const emptyTracking:Tracking={gesture:'NO_HAND',confidence:0,points:[],command:null};
const pretty=(n:number)=>Math.floor(n).toLocaleString('en-US');
export function App(){
 const mount=useRef<HTMLDivElement>(null);const sim=useRef(new Simulation()).current;const tracker=useRef(new HandTracker()).current;const audio=useRef(new AudioManager()).current;const world=useRef<World|null>(null);
 const [screen,setScreen]=useState<Screen>('menu');const screenRef=useRef<Screen>('menu');const [modal,setModal]=useState<'settings'|'help'|null>(null);const [settings,setSettings]=useState<Settings>(readSettings);const [tracking,setTracking]=useState<Tracking>(emptyTracking);const [active,setActive]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [graphicsError,setGraphicsError]=useState('');const [keyboard,setKeyboard]=useState(false);const keyboardRef=useRef(false);const [calibration,setCalibration]=useState<string[]>([]);const [tutorial,setTutorial]=useState(0);const tutorialRef=useRef(0);const [best,setBest]=useState(()=>readNumber('gd-best'));const bestRef=useRef(best);const [hud,setHud]=useState({speed:0,score:0,distance:0,lane:2,avoided:0,maxSpeed:0,elapsed:0,bonus:'',bonusTime:0});const [signal,setSignal]=useState<Command>('NEUTRAL');const signalTimer=useRef(0);const cameraGeneration=useRef(0);
 function go(next:Screen){screenRef.current=next;setScreen(next);}
 function action(command:Command){if(screenRef.current!=='race'&&screenRef.current!=='tutorial')return;sim.command(command);if(command==='LEFT'||command==='RIGHT'){audio.tone('lane');setSignal(command);clearTimeout(signalTimer.current);signalTimer.current=window.setTimeout(()=>setSignal('NEUTRAL'),1000);}if(command==='FIST')audio.tone('brake');if(screenRef.current==='tutorial'){const step=tutorialRef.current;if(step===0&&command==='LEFT'||step===1&&command==='RIGHT'){tutorialRef.current=step+1;setTutorial(step+1);}}}
 const actionRef=useRef(action);actionRef.current=action;
 useEffect(()=>{if(!mount.current)return;let frame=0;let last=performance.now(),lastUI=0;let oldPhase=sim.phase;let oldAvoided=0;
  try{world.current=new World(mount.current,sim);}catch(e){setGraphicsError(`3D graphics could not start. Enable WebGL / hardware acceleration in your browser. ${e instanceof Error?e.message:''}`);return;}
  const tick=(now:number)=>{const dt=Math.min((now-last)/1000,.05);last=now;sim.update(dt);world.current?.update(dt);audio.update(sim.speed,sim.phase==='race'||sim.phase==='tutorial');
   if(sim.phase==='crash'&&oldPhase!=='crash'){audio.tone('crash');const score=Math.max(bestRef.current,sim.score);bestRef.current=score;setBest(score);save('gd-best',String(score));screenRef.current='crash';setScreen('crash');}
   if(sim.avoided>oldAvoided)audio.tone('pass');oldAvoided=sim.avoided;oldPhase=sim.phase;
   if(screenRef.current==='tutorial'&&tutorialRef.current===2&&sim.braking&&sim.speed<.1){tutorialRef.current=3;setTutorial(3);}
   if(now-lastUI>70){setHud({speed:sim.speed,score:sim.score,distance:sim.distance,lane:sim.lane,avoided:sim.avoided,maxSpeed:sim.maxSpeed,elapsed:sim.elapsed,bonus:sim.lastBonus,bonusTime:sim.bonusTime});lastUI=now;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
  return()=>{cancelAnimationFrame(frame);clearTimeout(signalTimer.current);cameraGeneration.current++;tracker.dispose();world.current?.dispose();world.current=null;};
 },[sim,tracker,audio]);
 useEffect(()=>{tracker.mirror=settings.mirror;tracker.sensitivity=settings.sensitivity;audio.sfx=settings.sfx/100;audio.volume=settings.music/100;audio.muted=settings.muted;world.current?.quality(settings.graphics==='HIGH');save('gd-settings',JSON.stringify(settings));},[settings,tracker,audio]);
 useEffect(()=>{const keydown=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(e.code==='Escape'){if(screenRef.current==='race'||screenRef.current==='tutorial'){sim.phase='paused';go('paused');}else if(screenRef.current==='paused'){sim.phase=tutorialRef.current<3&& !keyboardRef.current?'tutorial':'race';go(sim.phase);}return;}if(!keyboardRef.current||e.repeat)return;if(['ArrowLeft','ArrowRight','KeyA','KeyD','Space'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft'||e.code==='KeyA')actionRef.current('LEFT');if(e.code==='ArrowRight'||e.code==='KeyD')actionRef.current('RIGHT');if(e.code==='Space')actionRef.current('FIST');};const keyup=(e:KeyboardEvent)=>{if(keyboardRef.current&&e.code==='Space')actionRef.current('NEUTRAL');};const blur=()=>{if(screenRef.current==='race'||screenRef.current==='tutorial'){sim.phase='paused';go('paused');}};window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);};},[sim]);
 async function enableCamera(){const generation=++cameraGeneration.current;setLoading(true);setError('');setCalibration([]);setKeyboard(false);keyboardRef.current=false;audio.init();try{await tracker.start(r=>{setTracking(r);if(screenRef.current==='calibration'&&r.points.length&&r.gesture!=='NO_HAND'){setCalibration(previous=>Array.from(new Set([...previous,'HAND',...(['LEFT','RIGHT','FIST'].includes(r.gesture)?[r.gesture]:[])])));}if(r.command&&!keyboardRef.current)actionRef.current(r.command);});if(cameraGeneration.current!==generation){tracker.stop();return;}setActive(true);go('calibration');}catch(e){if(cameraGeneration.current===generation){const name=e instanceof DOMException?e.name:'';setError(name==='NotAllowedError'?'Camera permission was denied. Allow camera access in your browser and try again.':name==='NotFoundError'?'No webcam found. Connect a camera, or try keyboard mode.':e instanceof Error?e.message:'Camera could not start. Please try again.');}}finally{if(cameraGeneration.current===generation)setLoading(false);}}
 function stopCamera(){cameraGeneration.current++;tracker.stop();setActive(false);setLoading(false);setTracking(emptyTracking);}
 function startRace(useKeyboard=keyboard,forceTutorial=false){audio.init();setKeyboard(useKeyboard);keyboardRef.current=useKeyboard;tracker.smoothing.reset();const needsTutorial=forceTutorial && readNumber('gd-tutorial-completed')!==1;sim.reset(needsTutorial);tutorialRef.current=needsTutorial?0:3;setTutorial(tutorialRef.current);setSignal('NEUTRAL');go(needsTutorial?'tutorial':'race');}
 function mainMenu(){sim.phase='menu';sim.traffic.forEach(c=>c.active=false);sim.braking=false;setModal(null);go('menu');}
 function pause(){sim.phase='paused';go('paused');}
 function resume(){sim.phase=tutorialRef.current<3?'tutorial':'race';go(sim.phase);sim.braking=false;tracker.smoothing.reset();setModal(null);}
 function click(){audio.init();audio.tone('click');}
 function set<K extends keyof Settings>(key:K,value:Settings[K]){setSettings(s=>({...s,[key]:value}));}
 const isDriving=['race','paused','tutorial','crash'].includes(screen);const stage=calibration.includes('LEFT')?calibration.includes('RIGHT')?'FIST':'RIGHT':'LEFT';
 return <div className={`app ${screen==='menu'?'on-menu':''}`}><div ref={mount} className="world"/><div className="world-vignette"/><div className="grain"/>
  <header className="topbar"><button className="brand" onClick={()=>{if(isDriving)pause();else mainMenu();}} aria-label="Gesture Drive home"><span className="brand-symbol"><i/><i/><i/></span><span>GESTURE<span className="brand-light">DRIVE</span><small>BEYOND THE WHEEL</small></span></button><nav><span className="build"><i/> SYSTEM ONLINE <b>v1.0</b></span><button className="icon-button" aria-label={settings.muted?'Unmute sound':'Mute sound'} onClick={()=>{click();set('muted',!settings.muted);}}>{settings.muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button><button className="icon-button" aria-label="Settings" onClick={()=>{click();if(screen==='race'||screen==='tutorial')pause();setModal('settings');}}><Settings2 size={18}/></button><button className="icon-button fullscreen" aria-label="Toggle fullscreen" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>{});}}><Maximize size={17}/></button></nav></header>
  {graphicsError&&<div className="graphics-error">{graphicsError}</div>}
  {screen==='menu'&&<main className="menu"><div className="hero"><div className="eyebrow"><span/> A NEW WAY TO DRIVE <b>01 / GESTURE SERIES</b></div><h1>NO WHEEL.<br/>JUST <span>INSTINCT.</span></h1><p className="hero-copy">Control the road with your hand.<br/>An open highway. Your next move.</p><div className="hero-actions"><button className="primary play-button" disabled={!!graphicsError} onClick={()=>{click();if(active)go('calibration');else go('access');}}><Play size={19} fill="currentColor"/> PLAY <ArrowUpRight size={23}/></button><button className="secondary" onClick={()=>{click();setModal('help');}}>HOW TO PLAY <CircleHelp size={17}/></button></div><button className="keyboard-link" disabled={!!graphicsError} onClick={()=>startRace(true)}><Keyboard size={14}/> No camera? Try keyboard mode <ArrowRight size={14}/></button><div className="hero-features"><div><Hand size={19}/><span>GESTURE CONTROL<small>Your hand is the controller</small></span></div><div><ShieldCheck size={19}/><span>100% ON DEVICE<small>Your camera stays private</small></span></div></div></div><aside className="menu-aside"><div className="edition">THE OPEN ROAD COLLECTION<span>DRIVE DIFFERENT.</span></div><CameraPreview tracker={tracker} result={tracking} active={active} mirror={settings.mirror} landmarks={settings.landmarks}/><div className="gesture-guide"><div className="section-label">THREE GESTURES. TOTAL CONTROL.</div><div><span className="gesture-icon"><MoveLeft size={20}/></span><span>Point left<small>Change lane</small></span><kbd>←</kbd></div><div><span className="gesture-icon"><MoveRight size={20}/></span><span>Point right<small>Change lane</small></span><kbd>→</kbd></div><div><span className="gesture-icon"><Hand size={20}/></span><span>Make a fist<small>Brake smoothly</small></span><kbd>■</kbd></div></div>{active&&<button className="text-button" onClick={stopCamera}>TURN OFF CAMERA</button>}</aside><div className="road-caption"><span className="tiny-lines">////</span><span>COASTAL HIGHWAY<small>04 LANES · ENDLESS POSSIBILITIES</small></span><Sun size={19}/><b>GOLDEN HOUR</b></div><div className="menu-bottom"><span>BUILT FOR YOUR INSTINCTS.</span><span>WEBCAM + A LITTLE COURAGE <ArrowUpRight size={13}/></span></div></main>}
  {isDriving&&<><div className="hud-left"><div className="section-label">SCORE</div><strong>{pretty(hud.score).padStart(5,'0')}</strong><div className="hud-separator"/><div className="distance"><Route size={15}/><span>{(hud.distance/1000).toFixed(2)} <small>KM</small></span></div><div className="best-small"><Trophy size={12}/> BEST {pretty(best)}</div></div><div className="race-right">{settings.preview&&!keyboard&&<CameraPreview tracker={tracker} result={tracking} active={active} mirror={settings.mirror} landmarks={settings.landmarks}/>}<button className="secondary pause-button" onClick={pause}><Pause size={16}/> PAUSE <kbd>ESC</kbd></button><span className="input-status">{keyboard?'KEYBOARD CONTROL':active?'● CAMERA ACTIVE':'CAMERA OFF'}</span></div><div className={`speedometer ${sim.braking?'braking':''}`}><div className="speed-ticks"/><div className="speed-inner"><span>{sim.braking?'BRAKING':'CRUISE CONTROL'}</span><strong>{Math.round(hud.speed).toString().padStart(3,'0')}</strong><small>KM / H</small></div></div><div className="lane-indicator"><span>LANE {hud.lane+1} / 4</span><div>{[0,1,2,3].map(l=><i key={l} className={l===hud.lane?'selected':''}/>)}</div></div><div className="race-hint">{keyboard?<><kbd>←</kbd><kbd>→</kbd> STEER <i/> <kbd>SPACE</kbd> BRAKE</>:<><Hand size={14}/> {tracking.gesture==='NO_HAND'?'NO HAND · HOLDING CURRENT LANE':'KEEP YOUR HAND IN FRAME'}</>}</div>{signal!=='NEUTRAL'&&<div className="lane-signal">{signal==='LEFT'?'← LEFT':'RIGHT →'}</div>}{hud.bonusTime>0&&<div className="bonus">{hud.bonus}</div>}<div className={`speed-lines ${hud.speed>125?'visible':''}`}/></>}
  {(screen==='access'||screen==='calibration')&&<div className="overlay"><section className="dialog camera-dialog"><button className="close" aria-label="Back to menu" onClick={()=>{if(loading)stopCamera();mainMenu();}}><X size={20}/></button><span className="dialog-tag">{screen==='access'?'CONNECT YOUR CONTROLLER':'A QUICK SYSTEM CHECK'}</span><div className="dialog-icon"><Camera size={28}/></div><h2>{screen==='access'?'Camera Access Required':calibration.length===4?'Calibration Complete':'Find your flow.'}</h2><p>{screen==='access'?'Your hand is all you need. Enable your webcam to get behind the wheel.':calibration.includes('HAND')?'Hand detected ✓':'Show your hand to the camera'}</p>{screen==='access'?<><div className="privacy-box"><ShieldCheck size={22}/><div>Your camera stays yours.<small>Processed locally. No recordings, uploads, or stored images.</small></div></div>{error&&<div className="error" role="alert">{error}</div>}<button className="primary wide" disabled={loading} onClick={enableCamera}><Camera size={17}/>{loading?'STARTING HAND TRACKING…':'ENABLE CAMERA'}<ArrowRight size={18}/></button><button className="text-button" onClick={()=>{stopCamera();startRace(true);}}>Use keyboard instead</button></>:<><CameraPreview tracker={tracker} result={tracking} active={active} mirror={settings.mirror} landmarks={settings.landmarks} large/><div className="calibration-steps">{(['LEFT','RIGHT','FIST']as const).map((g,i)=><div className={calibration.includes(g)?'complete':stage===g?'current':''} key={g}><span>{calibration.includes(g)?<Check size={17}/>:i+1}</span>{g==='FIST'?'Make a fist':`Point ${g.toLowerCase()}`}</div>)}</div><p className="small-copy">Hold each gesture steadily. Return to an open hand between gestures.</p><button className="primary wide" disabled={calibration.length!==4} onClick={()=>startRace(false,true)}>START RACE <ArrowRight size={18}/></button></>}</section></div>}
  {screen==='tutorial'&&<section className="tutorial-panel"><span className="dialog-tag">DRIVING SCHOOL · {Math.min(tutorial+1,3)} / 3</span><div className="tutorial-icon">{tutorial===0?<MoveLeft/>:tutorial===1?<MoveRight/>:tutorial===2?<Hand/>:<Check/>}</div><h2>{tutorial===0?'Point LEFT':tutorial===1?'Point RIGHT':tutorial===2?'Make a FIST':"YOU’RE READY"}</h2><p>{tutorial<2?'Change to the next lane with your hand.':tutorial===2?'Hold your fist until the car stops.':'Perfect. The highway is yours.'}</p><div className="step-dots">{[0,1,2].map(i=><i key={i} className={i<tutorial?'done':i===tutorial?'now':''}/>)}</div>{tutorial===3&&<button className="primary wide" onClick={()=>{save('gd-tutorial-completed','1');startRace(false);}}>START DRIVE <ArrowRight size={18}/></button>}</section>}
  {(screen==='paused'||screen==='crash')&&<div className="overlay"><section className={`dialog ${screen==='crash'?'crash-dialog':''}`}><span className="dialog-tag">{screen==='crash'?'EVERY DRIVE IS A NEW STORY':'TAKE A BREATHER'}</span><div className="dialog-icon">{screen==='crash'?<Gauge size={30}/>:<Pause size={28}/>}</div><h2>{screen==='crash'?'CRASH!':'PAUSED'}</h2><p>{screen==='crash'?'Shake it off. There’s more road ahead.':'The road will wait for you.'}</p>{screen==='crash'?<><div className="result-score"><span>FINAL SCORE</span><strong>{pretty(hud.score)}</strong></div><div className="results">{[['DISTANCE',`${(hud.distance/1000).toFixed(2)} km`],['BEST SCORE',pretty(best)],['CARS AVOIDED',hud.avoided],['MAX SPEED',`${Math.round(hud.maxSpeed)} km/h`]].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div><button className="primary wide" onClick={()=>startRace()}><RotateCcw size={17}/> RESTART <ArrowRight size={18}/></button></>:<><button className="primary wide" onClick={resume}><Play size={17}/> RESUME <ArrowRight size={18}/></button><button className="secondary wide" onClick={()=>startRace()}><RotateCcw size={16}/> RESTART</button><button className="secondary wide" onClick={()=>setModal('settings')}><Settings2 size={16}/> SETTINGS</button></>}<button className="text-button" onClick={mainMenu}>MAIN MENU</button></section></div>}
  {modal&&<div className="overlay modal-layer"><section className="dialog settings-dialog"><button className="close" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={20}/></button><span className="dialog-tag">MAKE IT YOUR DRIVE</span><h2>{modal==='settings'?'SETTINGS':'HOW TO PLAY'}</h2>{modal==='help'?<><p>Four lanes. Endless highway. One controller: you.</p><div className="help-list"><div><MoveLeft/><span><b>Point left or right</b><small>Extend your index finger sideways to change one lane. Open your hand before pointing again.</small></span></div><div><Hand/><span><b>Close your fist to brake</b><small>Hold until stopped. Open your hand to accelerate. A missing hand keeps your last driving state.</small></span></div><div><Trophy/><span><b>Find the clear lane</b><small>Overtake traffic for +50 points. Close calls earn +100. Distance earns 2 points per meter.</small></span></div><div><Keyboard/><span><b>Keyboard alternative</b><small>← / → or A / D to steer. Hold Space to brake. Escape pauses the race.</small></span></div></div><button className="primary wide" onClick={()=>setModal(null)}>GOT IT <Check size={18}/></button></>:<><div className="settings-section"><span>SOUND</span><button className="toggle-label" onClick={()=>set('muted',!settings.muted)}>Mute all audio <i className={`toggle ${settings.muted?'on':''}`}/></button>{(['music','sfx']as const).map(k=><label className="slider-label" key={k}><span>{k==='music'?'Music Volume':'SFX Volume'} <b>{settings[k]}%</b></span><input type="range" min="0" max="100" value={settings[k]} onChange={e=>set(k,Number(e.target.value))}/></label>)}</div><div className="settings-section"><span>GRAPHICS & CONTROL</span><label className="select-label">Graphics<select value={settings.graphics} onChange={e=>set('graphics',e.target.value)}><option>HIGH</option><option>LOW</option></select></label><label className="select-label">Gesture Sensitivity<select value={settings.sensitivity} onChange={e=>set('sensitivity',e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label></div><div className="settings-section"><span>CAMERA</span>{(['landmarks','preview','mirror']as const).map(k=><button className="toggle-label" key={k} onClick={()=>set(k,!settings[k])}>{k==='landmarks'?'Show Hand Landmarks':k==='preview'?'Show Camera Preview':'Mirror Camera'}<i className={`toggle ${settings[k]?'on':''}`}/></button>)}{active?<button className="text-button danger" onClick={stopCamera}>TURN OFF CAMERA</button>:<button className="text-button" disabled={loading} onClick={()=>{setModal(null);go('access');}}>ENABLE CAMERA</button>}</div><button className="primary wide" onClick={()=>setModal(null)}>SAVE & CLOSE <Check size={18}/></button></>}</section></div>}
  <footer className="footer"><span><i className={active?'live':''}/>{active?'CAMERA ACTIVE':'CAMERA OFF'}<span className="footer-divider">/</span> LOCAL PROCESSING ONLY</span><span>GESTURE DRIVE <b>© 2026</b></span></footer>
 </div>;
}
